name: CLI
env:
  PUBLISH_DIR: /home/runner/work/SNQueue/SNQueue/SNQueue/Server/bin/Release/net7.0/publish/
on:
  push:
    branches: [ master ]
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Publish application
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Install .NET WASM Build Tools
      run: dotnet workload install wasm-tools
    - name: Publish .NET Core Project
      run: dotnet publish -c Release
    - name: Rewrite base href
      if: success()
      uses: SteveSandersonMS/ghaction-rewrite-base-href@v1
      with:
        html_path: ${{ env.PUBLISH_DIR }}/index.html
        base_href: BASE_URL or REPOSITORY_NAME
    - name: Add .nojekyll file
      run: touch ${{ env.PUBLISH_DIR }}/.nojekyll
    - name: Commit to GitHub pages Repo
      if: success()
      uses: crazy-max/ghaction-github-pages@v1.5.1
      with:
        target_branch: gh-pages
        build_dir: ${{ env.PUBLISH_DIR }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
